### PR TITLE
Add context menu items to start capture

### PR DESCRIPTION
**Pull request by pastak**

### CODE REVIEW

**Comment by rakusai** [comment]
Why
Capture -> English
部品 -> Japanese?

Maybe "Gyazo" is good?

**Comment by rakusai** [comment]
Gyazoでキャプチャ
Capture with Gyazo

**Comment by pastak** [comment]
update wording [https://gyazo.com/d4ca026cb7770aff54b2225150c05233](https://gyazo.com/d4ca026cb7770aff54b2225150c05233)

**Comment by pastak** [comment]
## Setting enabled

[https://gyazo.com/da29212efc131513f3443e68208b6a9d](https://gyazo.com/da29212efc131513f3443e68208b6a9d)

## Setting disabled

[https://gyazo.com/763fdc6d0a8f73d36f60b6fbfdc563fe](https://gyazo.com/763fdc6d0a8f73d36f60b6fbfdc563fe)

**Pull request merged**
